version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: amn_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amn
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: amn_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
